// Generates RunOil brand assets from the canonical mark in the brand book.
// - Extracts the hL/hR diagonal-seam ring paths (single source of truth).
// - Emits app/lib/brand-mark.ts (paths reused by the in-app Logo component).
// - Emits public/favicon.svg + a rasterized PNG icon set + web manifest.
//
// Run: node scripts/brand-assets.mjs
import { readFile, writeFile } from "node:fs/promises";
import sharp from "sharp";

const NAVY = "#0B2545";
const VIOLET = "#7C3AED";
const LILAC = "#A78BFA";

const html = await readFile("docs/brand/brand-book.html", "utf8");
const grab = (id) => {
  const m = html.match(new RegExp(`id="${id}"\\s+d="([^"]+)"`));
  if (!m) throw new Error(`mark path ${id} not found in brand book`);
  return m[1];
};
const HL = grab("hL");
const HR = grab("hR");

// 1. Path constants for the React Logo component.
await writeFile(
  "app/lib/brand-mark.ts",
  `// AUTO-GENERATED by scripts/brand-assets.mjs from docs/brand/brand-book.html.
// The RunOil mark: a ring split by a diagonal seam into two halves — navy
// leads, violet completes. Do not edit by hand; re-run the script.
export const MARK_VIEWBOX = "0 0 100 100";
export const MARK_LEFT_PATH = ${JSON.stringify(HL)};
export const MARK_RIGHT_PATH = ${JSON.stringify(HR)};
`,
);

// 2. favicon.svg — the bare mark itself (the split "O"), exactly as in the
// wordmark: navy + violet. Adapts to white + lilac on dark browser chrome so
// the navy half never disappears.
const faviconSvg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100" width="100" height="100">
  <style>
    .l { fill: ${NAVY}; } .r { fill: ${VIOLET}; }
    @media (prefers-color-scheme: dark) { .l { fill: #FFFFFF; } .r { fill: ${LILAC}; } }
  </style>
  <path class="l" d="${HL}"/>
  <path class="r" d="${HR}"/>
</svg>
`;
await writeFile("public/favicon.svg", faviconSvg);

// A transparent two-tone mark (navy + violet) for embedding/large contexts.
await writeFile(
  "public/mark.svg",
  `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100" width="100" height="100">
  <path d="${HL}" fill="${NAVY}"/>
  <path d="${HR}" fill="${VIOLET}"/>
</svg>
`,
);

// 3. PNG icon set — the mark on a clean white tile (the primary lockup; opaque
// for home-screen / PWA contexts, legible on any background).
const tileSvg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100" width="100" height="100">
  <rect width="100" height="100" rx="22" fill="#FFFFFF"/>
  <g transform="translate(13 13) scale(0.74)">
    <path d="${HL}" fill="${NAVY}"/>
    <path d="${HR}" fill="${VIOLET}"/>
  </g>
</svg>
`;
const png = (size) => sharp(Buffer.from(tileSvg)).resize(size, size).png();
await Promise.all([
  png(32).toFile("public/favicon-32.png"),
  png(180).toFile("public/apple-touch-icon.png"),
  png(192).toFile("public/icon-192.png"),
  png(512).toFile("public/icon-512.png"),
]);

// 4. Web manifest.
await writeFile(
  "public/site.webmanifest",
  JSON.stringify(
    {
      name: "RunOil",
      short_name: "RunOil",
      icons: [
        { src: "/icon-192.png", sizes: "192x192", type: "image/png" },
        { src: "/icon-512.png", sizes: "512x512", type: "image/png" },
      ],
      theme_color: NAVY,
      background_color: "#ffffff",
      display: "standalone",
    },
    null,
    2,
  ),
);

console.log("Brand assets generated.");
